Repository mlund/faunus, pull requests merged in 2020-07, with the labels that each got.

#299 Refactor random.h
  src/core.cpp
  src/core.h
  src/geometry.h
  src/molecule.cpp
  src/molecule.h
  src/potentials.cpp
  src/random.cpp
  src/random.h
Labels: refactoring :gear:

#300 Fix speciation check for full or empty groups
  src/speciation.cpp
Labels: bug :bug:, fix :wrench:

#302 Nonbonded splined refactor
  .clang-tidy
  docs/_docs/energy.md
  docs/schema.yml
  examples/cluster/cluster.yml
  src/energy.cpp
  src/potentials.cpp
  src/potentials.h
Labels: refactoring :gear:

#303 Legendre
  src/auxiliary.h
Labels: enhancement :muscle:, refactoring :gear:

#304 Refactor MonteCarloSimulation class
  examples/pythontest.py
  src/energy.cpp
  src/energy.h
  src/externalpotential.cpp
  src/externalpotential.h
  src/faunus.cpp
  src/group.h
  src/montecarlo.cpp
  src/montecarlo.h
  src/pyfaunus.cpp
  src/space.cpp
  src/space.h
  src/speciation.cpp
  src/speciation.h
Labels: refactoring :gear:

#309 Introduced overwrite option to savestate
  docs/schema.yml
  src/analysis.cpp
  src/analysis.h
Labels: enhancement :muscle:

#307 Update crankshaft in schema.yml
  docs/schema.yml
  src/move.cpp
Labels: fix :wrench:

#308 Allow gzip for qrtraj and minor refactoring
  docs/_docs/analysis.md
  docs/schema.yml
  src/analysis.cpp
  src/analysis.h
  src/io.cpp
Labels: enhancement :muscle:

#311 Clean io.h
  docs/schema.yml
  src/analysis.cpp
  src/io.cpp
  src/io.h
Labels: refactoring :gear:

#310 Refactor widom analysis
  .idea/inspectionProfiles/Project_Default.xml
  src/analysis.cpp
  src/analysis.h
  src/molecule.cpp
  src/molecule.h
  src/space.cpp
  src/space.h
Labels: bug :bug:, refactoring :gear:

#312 Fix (un)shifted yukawa
  docs/_docs/energy.md
  docs/schema.yml
  src/potentials.cpp
  src/potentials_test.h
Labels: fix :wrench:

#316 Clarify keyword `inactive` in manual
  docs/_docs/topology.md
Labels: enhancement :muscle:

#314 Split auxiliary.h
  .idea/codeStyles/Project.xml
  src/CMakeLists.txt
  src/analysis.h
  src/aux/equidistant_table.h
  src/aux/error_function.h
  src/aux/exp_function.h
  src/aux/invsqrt_function.h
  src/aux/legendre.h
  src/aux/multimatrix.h
  src/aux/pairmatrix.h
  src/aux/pow_function.h
  src/aux/table_1d.h
  src/aux/table_2d.h
  src/aux/timers.h
  src/auxiliary.h
  src/bonds.h
  src/clustermove.h
  src/energy.h
  src/externalpotential.h
  src/geometry.cpp
  src/move.h
  src/multipole.h
  src/penalty.h
  src/potentials.cpp
  src/potentials.h
  src/unittests.cpp
Labels: refactoring :gear:

#318 Use double in units user defined literals
  src/units.h
Labels: refactoring :gear:

#317 Enable integer selection for inactive molecules
  docs/_docs/topology.md
  docs/schema.yml
  src/group.h
  src/montecarlo.cpp
  src/space.cpp
  src/space.h
  src/space_test.h
Labels: enhancement :muscle:

#315 Refactor structure loading policy
  src/io.cpp
  src/io.h
  src/molecule.cpp
  src/molecule.h
  src/space.cpp
Labels: refactoring :gear:
