Repository mlund/faunus, pull requests merged in 2020-01, with the labels that each got.

#234 Add Gouy Chapman external electric potential
  docs/_docs/energy.md
  src/externalpotential.cpp
  src/externalpotential.h
  src/geometry.cpp
  src/geometry.h
Labels: enhancement :muscle:

#235 Fix `ensphere` and add `to_disk` for molecular topology
  docs/_docs/topology.md
  src/geometry.cpp
  src/geometry.h
  src/molecule.cpp
Labels: enhancement :muscle:, fix :wrench:

#236 Virtual translation move for force calculation
  docs/_docs/analysis.md
  src/analysis.cpp
  src/analysis.h
Labels: enhancement :muscle:

#238 Compare against theoretical values in the chain example
  examples/chain/chain.out.json
Labels: fix :wrench:

#239 Fix the minimal example
  examples/minimal/minimal.out.json
  examples/minimal/minimal.state.json
  examples/minimal/minimal.yml
Labels: fix :wrench:

#237 Refactor io functions to use fmt over printf
  src/CMakeLists.txt
  src/analysis.cpp
  src/io.cpp
  src/io.h
  src/io_test.h
  src/molecule.cpp
  src/space.cpp
  src/space.h
  src/space_test.h
  src/unittests.cpp
Labels: refactoring :gear:

#240 Support for JSON schema
  .idea/codeStyles/Project.xml
  docs/_docs/energy.md
  docs/_docs/install.md
  docs/schema.yml
  examples/chain/chain.yml
  examples/polymers/polymers.yml
  examples/swapconf/swapconf.yml
  scripts/environment.yml
  scripts/inject_schema.py
  scripts/yason.py
  src/CMakeLists.txt
Labels: enhancement :muscle:
