Repository mlund/faunus, pull requests merged in 2020-09, with the labels that each got.

#320 Cleanup multipole and sample active groups only
  src/analysis.cpp
  src/analysis.h
Labels: refactoring :gear:

#325 Enable Intel Threading Building Blocks
  cmake/ExternalTools.cmake
  docs/_docs/install.md
  src/energy.h
Labels: enhancement :muscle:

#327 Allow cuboids in scattering analysis
  docs/_docs/analysis.md
  src/analysis.cpp
  src/scatter.cpp
  src/scatter.h
Labels: enhancement :muscle:

#329 Fix AAM file reader (atoms begin at line 2)
  src/io.cpp
Labels: fix :wrench:

#330 Fix VirtualVolumeAnalysis (Space is a reference)
  src/analysis.h
Labels: fix :wrench:
