Repository mlund/faunus, pull requests merged in 2020-02, with the labels that each got.

#242 Add Cereal serialization and compressed SpaceTrajectory
  CMakeLists.txt
  docs/_docs/analysis.md
  docs/schema.yml
  src/CMakeLists.txt
  src/analysis.cpp
  src/analysis.h
  src/aux/eigen_cerealisation.hpp
  src/aux/eigensupport.h
  src/average.h
  src/geometry.h
  src/geometry_test.h
  src/group.h
  src/group_test.h
  src/io_test.h
  src/particle.h
  src/particle_test.h
Labels: enhancement :muscle:

#245 Fix compilation error related to Cereal
  scripts/environment.yml
  src/analysis.cpp
  src/io.h
Labels: fix :wrench:

#243 Scattering OMP parallelisation
  CMakeLists.txt
  docs/_docs/analysis.md
  docs/_docs/install.md
  docs/_docs/running.md
  docs/schema.yml
  src/CMakeLists.txt
  src/analysis.cpp
  src/analysis.h
  src/auxiliary.h
  src/auxiliary_test.h
  src/geometry.h
  src/io.h
  src/scatter.h
  src/scatter_test.h
  src/unittests.cpp
Labels: enhancement :muscle:

#247 Refactoring of Ewald summation policies and Energy class
  docs/_docs/energy.md
  docs/schema.yml
  examples/water/ewald.yml
  src/CMakeLists.txt
  src/energy.cpp
  src/energy.h
  src/energy_test.h
Labels: refactoring :gear:

#250 Gracefully handle removal attempt on empty group
  src/speciation.cpp
  src/speciation.h
Labels: bug :bug:

#252 Additional speciation tests
  docs/_docs/energy.md
  docs/schema.yml
  examples/speciation_group/speciation_group.out.json
  examples/speciation_group/speciation_group.state.json
  examples/speciation_group/speciation_group.yml
  examples/speciation_swapconf/speciation_swapconf.out.json
  examples/speciation_swapconf/speciation_swapconf.state.json
  examples/speciation_swapconf/speciation_swapconf.yml
  examples/titration/titration.out.json
  examples/titration/titration.state.json
  examples/titration/titration.yml
  src/CMakeLists.txt
  src/reactioncoordinate.cpp
Labels: enhancement :muscle:

#257 Refactor nonbonded energy
  docs/_docs/energy.md
  src/atomdata.h
  src/energy.cpp
  src/energy.h
  src/group.h
  src/units.h
Labels: refactoring :gear:

#258 Skip lengthy benchmarks in unittests
  src/CMakeLists.txt
Labels: fix :wrench:
