Repository mlund/faunus, pull requests merged in 2020-06, with the labels that each got.

#287 Moltransrot abort if atomic group
  src/move.cpp
  src/move.h
Labels: bug :bug:

#288 Enable JSON output for nonbonded energy
  src/energy.cpp
  src/energy.h
  src/potentials.cpp
  src/potentials.h
Labels: bug :bug:

#290 Store simulation duration in json output
  src/faunus.cpp
Labels: enhancement :muscle:

#289 Enable gzip compression for systemenergy analysis
  docs/_docs/analysis.md
  src/analysis.cpp
  src/analysis.h
  src/io.cpp
  src/io.h
Labels: enhancement :muscle:

#291 Anisotropic volume perturbation
  docs/_docs/analysis.md
  docs/_docs/moves.md
  docs/schema.yml
  src/analysis.cpp
  src/analysis.h
  src/geometry.h
  src/io.cpp
  src/io.h
  src/space.cpp
  src/space.h
Labels: enhancement :muscle:

#292 Filename increment for savestate
  docs/_docs/analysis.md
  docs/schema.yml
  src/analysis.cpp
  src/analysis.h
Labels: enhancement :muscle:

#296 Refactor EnergyBase for increased readability
  docs/schema.yml
  src/energy.cpp
  src/energy.h
  src/externalpotential.cpp
  src/externalpotential.h
  src/montecarlo.cpp
Labels: refactoring :gear:

#293 Add reciprocal ewald force
  src/energy.cpp
  src/energy.h
Labels: enhancement :muscle:

#295 Forces for bonded interactions for use with Langevin dynamics
  src/bonds.cpp
  src/bonds.h
  src/bonds_test.h
  src/energy.cpp
  src/energy.h
  src/speciation.cpp
Labels: enhancement :muscle:

#297 Upgrade external libraries
  CMakeLists.txt
Labels: enhancement :muscle:
