Repository mlund/faunus, pull requests merged in 2021-08, with the labels that each got.

#347 Refactor from_json for AtomData vector
  docs/schema.yml
  src/atomdata.cpp
  src/atomdata.h
  src/core.cpp
  src/core.h
  src/faunus.cpp
  src/molecule.cpp
  src/molecule.h
  src/potentials.cpp
  src/pyfaunus.cpp
  src/space.cpp
Labels: refactoring :gear:

#379 Electricpotential analysis
  docs/_docs/analysis.md
  docs/schema.yml
  src/CMakeLists.txt
  src/analysis.cpp
  src/analysis.h
  src/aux/sparsehistogram.h
  src/move.h
  src/potentials.cpp
  src/potentials.h
Labels: enhancement :muscle:

#386 Use strongly typed enums in Geometry namespace
  src/analysis.cpp
  src/analysis.h
  src/energy.cpp
  src/externalpotential.cpp
  src/geometry.cpp
  src/geometry.h
  src/pyfaunus.cpp
  src/reactioncoordinate.cpp
  src/space.cpp
  src/space.h
Labels: refactoring :gear:

#387 Refactor Average class
  src/analysis.cpp
  src/analysis.h
  src/aux/equidistant_table.h
  src/average.cpp
  src/average.h
  src/externalpotential.cpp
  src/move.cpp
  src/move.h
  src/speciation.cpp
Labels: enhancement :muscle:, refactoring :gear:

#385 Add fixed upper limit for pair energy storage
  src/energy.h
Labels: enhancement :muscle:

#388 Unsigned integers for particle/group index in space
  src/energy.h
  src/space.cpp
  src/space.h
Labels: refactoring :gear:
