Repository mlund/faunus, pull requests merged in 2021-03, with the labels that each got.

#348 Refactor penalty energy and reaction coordinates
  src/CMakeLists.txt
  src/analysis.cpp
  src/atomdata.cpp
  src/auxiliary.h
  src/core.cpp
  src/energy.h
  src/molecule.cpp
  src/penalty.cpp
  src/penalty.h
  src/reactioncoordinate.cpp
  src/reactioncoordinate.h
  src/tensor.cpp
Labels: refactoring :gear:

#349 Fix failing unittests
  examples/CMakeLists.txt
  examples/temper/temper.ipynb
  examples/titration/titration.out.json
  scripts/environment.yml
  src/analysis.cpp
Labels: fix :wrench:

#350 Virtualtrans refactor
  docs/_docs/analysis.md
  docs/schema.yml
  examples/virial/virial.ipynb
  examples/virial/virial.yml
  src/analysis.cpp
  src/analysis.h
  src/io.cpp
  src/io.h
Labels: refactoring :gear:

#351 Add base class for perturbation analysis
  src/analysis.cpp
  src/analysis.h
Labels: refactoring :gear:

#353 Analysis cleanup
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  src/analysis.cpp
  src/analysis.h
  src/geometry.cpp
  src/geometry.h
  src/molecule.cpp
  src/space.h
Labels: refactoring :gear:

#352 Lnps
  docs/_docs/analysis.md
  docs/schema.yml
  src/analysis.cpp
  src/geometry.h
  src/reactioncoordinate.cpp
Labels: enhancement :muscle:
