Repository mlund/faunus, pull requests merged in 2021-11, with the labels that each got.

#397 Sasa celllist
  .zenodo.json
  docs/_docs/docs.md
  docs/_docs/energy.md
  docs/schema.yml
  src/celllistimpl.h
  src/energy.cpp
  src/energy.h
  src/group.cpp
  src/sasa.cpp
  src/sasa.h
Labels: enhancement :muscle:

#398 Use MPL library for MPI handling
  cmake/ExternalTools.cmake
  docs/_docs/moves.md
  examples/temper/temper.ipynb
  src/CMakeLists.txt
  src/energy.cpp
  src/faunus.cpp
  src/montecarlo.cpp
  src/montecarlo.h
  src/move.cpp
  src/move.h
  src/mpicontroller.cpp
  src/mpicontroller.h
  src/penalty.cpp
  src/penalty.h
  src/pyfaunus.cpp
Labels: enhancement :muscle:, code quality :gear:

#400 Minor shift towards std::string_view
  src/analysis.cpp
  src/analysis.h
  src/atomdata.cpp
  src/atomdata.h
  src/core.cpp
  src/core.h
  src/io.cpp
  src/io.h
  src/montecarlo.cpp
  src/move.cpp
  src/move.h
  src/speciation.cpp
  src/speciation.h
  src/units.cpp
  src/units.h
Labels: code quality :gear:

#401 Density refactor
  docs/_docs/analysis.md
  examples/calciumhydroxide/calciumhydroxide.out.json
  examples/calciumhydroxide/calciumhydroxide.yml
  examples/calciumhydroxide_molecular/calciumhydroxide_molecular.out.json
  examples/calciumhydroxide_molecular/calciumhydroxide_molecular.yml
  examples/phosphate/phosphate.out.json
  examples/phosphate/phosphate.state.json
  examples/phosphate/phosphate.yml
  examples/sodiumphosphate/sodiumphosphate.out.json
  examples/sodiumphosphate/sodiumphosphate.state.json
  examples/sodiumphosphate/sodiumphosphate.yml
  examples/speciation/speciation.out.json
  examples/speciation/speciation.yml
  examples/titration/titration.out.json
  examples/titration/titration.yml
  src/analysis.cpp
  src/analysis.h
  src/space.cpp
  src/space.h
Labels: code quality :gear:, fix :wrench:
